config/routes.rb
Rails.application.routes.draw do
  resources :recipes

end

app/models/ingredient.rb
# create_table :ingredients do |t|
#   t.string  :substance,     null: false
#   t.decimal :quantity,      null: false,  default: 0
#   t.string  :quantity_unit, null: false,  default: 'tablespoon'
#   t.integer :recipe_id,     null: false
# end

require 'unitwise'
require 'unitwise/ext'

class Ingredient < ActiveRecord::Base
  validates :substance, presence: true
  validates :quantity, numericality: { :greater_than => 0.00 }
  validates :quantity_unit, presence: true

  def quantity
    read_attribute(:quantity).convert_to(self.quantity_unit)
  end

  def quantity=(value)
    write_attribute :quantity, value.to_tablespoon
    if value.respond_to?(:unit)
      self.quantity_unit = value.unit.to_s
    end
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	validates :name, :length => { :minimum => 5 }
	validates :preparation_time, :numericality => { :only_integer => true, :greater_than_or_equal_to => 60 }
	validates :difficulty, :numericality => { :only_integer => true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5 }
	validates :cooking_time, :numericality => { :only_integer => true }
	validates :rest_time, :numericality => { :only_integer => true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :cooking_time, :difficulty, :rest_time, :preparation_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iCook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe, :html => { :class => "form-horizontal recipe" } do |f| %>

    <% if @recipe.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@recipe[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :cooking_time, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cooking_time, :class => 'form-control' %>
    </div>
    <%= error_span(@recipe[:cooking_time]) %>
  </div>
  <div class="control-group">
    <%= f.label :difficulty, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :difficulty, :class => 'form-control' %>
    </div>
    <%= error_span(@recipe[:difficulty]) %>
  </div>
  <div class="control-group">
    <%= f.label :rest_time, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rest_time, :class => 'form-control' %>
    </div>
    <%= error_span(@recipe[:rest_time]) %>
  </div>
  <div class="control-group">
    <%= f.label :preparation_time, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :preparation_time, :class => 'form-control' %>
    </div>
    <%= error_span(@recipe[:preparation_time]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            recipes_path, :class => 'btn btn-default' %>

<% end %>

app/views/recipes/edit.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:cooking_time) %></th>
      <th><%= model_class.human_attribute_name(:difficulty) %></th>
      <th><%= model_class.human_attribute_name(:rest_time) %></th>
      <th><%= model_class.human_attribute_name(:preparation_time) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.id, recipe_path(recipe) %></td>
        <td><%= recipe.name %></td>
        <td><%= recipe.cooking_time %></td>
        <td><%= recipe.difficulty %></td>
        <td><%= recipe.rest_time %></td>
        <td><%= recipe.preparation_time %></td>
        <td><%=l recipe.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_recipe_path(recipe), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      recipe_path(recipe),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_recipe_path,
            :class => 'btn btn-primary' %>

app/views/recipes/new.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @recipe.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cooking_time) %>:</strong></dt>
  <dd><%= @recipe.cooking_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:difficulty) %>:</strong></dt>
  <dd><%= @recipe.difficulty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rest_time) %>:</strong></dt>
  <dd><%= @recipe.rest_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:preparation_time) %>:</strong></dt>
  <dd><%= @recipe.preparation_time %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              recipes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_recipe_path(@recipe), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              recipe_path(@recipe),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>